# Generated by Django 5.2.7 on 2025-11-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]
	
	operations = [
		migrations.CreateModel(
			name='Task',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('description', models.TextField(blank=True)),
				('status', models.CharField(
					choices=[('done', 'Виконано'), ('pending', 'Не виконано')],
					default='pending', max_length=20)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('deadline', models.DateTimeField(blank=True, null=True)),
				('user',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to=settings.AUTH_USER_MODEL)),
			],
		),
	]
