# Generated by Django 5.2.7 on 2025-11-18 21:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('tasks', '0001_initial'),
	]
	
	operations = [
		migrations.RemoveField(
			model_name='task',
			name='created_at',
		),
		migrations.RemoveField(
			model_name='task',
			name='deadline',
		),
		migrations.AddField(
			model_name='task',
			name='due_date',
			field=models.DateField(default=datetime.date.today),
		),
		migrations.AlterField(
			model_name='task',
			name='status',
			field=models.CharField(
				choices=[('pending', 'Pending'), ('done', 'Done')],
				default='pending', max_length=10),
		),
	]
