# Generated by Django 5.2.7 on 2025-11-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('tasks', '0002_remove_task_created_at_remove_task_deadline_and_more'),
	]
	
	operations = [
		migrations.AddField(
			model_name='task',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
