# Generated by Django 5.2.7 on 2025-11-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]
	
	operations = [
		migrations.CreateModel(
			name='Genre',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100, unique=True)),
			],
		),
		migrations.CreateModel(
			name='Movie',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('description', models.TextField()),
				('release_date', models.DateField()),
				('rating', models.FloatField(default=0.0)),
				('genres', models.ManyToManyField(related_name='movies',
				                                  to='movies.genre')),
			],
		),
		migrations.CreateModel(
			name='Review',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('text', models.TextField()),
				('score', models.IntegerField()),
				('movie',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='reviews', to='movies.movie')),
				('user',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to=settings.AUTH_USER_MODEL)),
			],
		),
	]
