# Generated by Django 5.2.7 on 2025-11-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
	]
	
	operations = [
		migrations.CreateModel(
			name='Course',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('description', models.TextField()),
			],
		),
		migrations.CreateModel(
			name='Student',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100)),
				('email', models.EmailField(max_length=254, unique=True)),
			],
		),
		migrations.CreateModel(
			name='ExamResult',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('score', models.FloatField()),
				('course',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='results',
				                   to='students.course')),
				('student',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='results',
				                   to='students.student')),
			],
		),
		migrations.CreateModel(
			name='Enrollment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('enrolled_at', models.DateTimeField(auto_now_add=True)),
				('course',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='enrollments',
				                   to='students.course')),
				('student',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='enrollments',
				                   to='students.student')),
			],
		),
	]
