# Generated by Django 5.2.7 on 2025-11-12 15:57

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
	]
	
	operations = [
		migrations.CreateModel(
			name='CustomModel',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('name', core.models.UpperTextField(max_length=100)),
				('data', models.JSONField(default=dict)),
			],
		),
		migrations.CreateModel(
			name='RelatedModel',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('value', models.CharField(max_length=100)),
				('custom',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   related_name='related',
				                   to='core.custommodel')),
			],
		),
	]
