# Generated by Django 5.2.7 on 2025-10-28 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]
	
	operations = [
		migrations.CreateModel(
			name='Category',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100, unique=True)),
				('description', models.TextField()),
			],
		),
		migrations.CreateModel(
			name='Ad',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('description', models.TextField()),
				('price', models.DecimalField(decimal_places=2, max_digits=10,
				                              validators=[
					                              django.core.validators.MinValueValidator(
						                              0.01)])),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('is_active', models.BooleanField(default=True)),
				('user',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to=settings.AUTH_USER_MODEL)),
				('category',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to='board.category')),
			],
		),
		migrations.CreateModel(
			name='Comment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('content', models.TextField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('ad',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to='board.ad')),
				('user',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
				                   to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.CreateModel(
			name='UserProfile',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True,
				                           serialize=False, verbose_name='ID')),
				('phone', models.CharField(blank=True, max_length=20)),
				('address', models.TextField(blank=True)),
				('user', models.OneToOneField(
					on_delete=django.db.models.deletion.CASCADE,
					to=settings.AUTH_USER_MODEL)),
			],
		),
	]
